### ISSUE TITLE
The documentation for the latest version of this package is missing on Hackage. 

### ISSUE THREAD

**Issue by expipiplus1** [finlay/servant-github#4]
The documentation for the latest version of this package is missing on Hackage. It's possible that Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please? Note that this requires cabal-install >= 1.24

Thanks!

**Comment by domenkozar** [comment]
Fixed: https://hackage.haskell.org/package/servant-github

**Comment by finlay** [comment]
Looks okay to me. I am going to close this issue.

**Comment by expipiplus1** [comment]
Thanks!
